tasks:
  - name: dependencies
    init: >
      npm i &&
      gp sync-done bundle
  - name: dev server
    init: gp sync-await bundle
    command: npx @tarojs/cli@3.3.9 build --type h5 --watch

ports:
  - port: 10086
    onOpen: open-preview
