tasks:
  - name: dependencies
    init: >
      npm i &&
      gp sync-done bundle
  - name: dev server
    init: gp sync-await bundle
    command: npm run dev:h5

ports:
  - port: 10086
    onOpen: open-preview
